In [1]:
"""

"""
from os import environ
environ["OPENBLAS_NUM_THREADS"] = "1"
import numpy as np
import matplotlib.pyplot as plt
from PDE import *

In numerical relativity, gauge conditions are specific choices of coordinate systems (or gauges) that simplify the equations of general relativity and help maintain numerical stability during simulations. These conditions determine how the spacetime coordinates evolve during the simulation, which can significantly impact the accuracy and stability of the numerical solution.

Two critical gauge conditions in numerical relativity are:

Lapse Function (α): Determines the rate of progression of time.

Shift Vector (β^i): Determines how the spatial coordinates shift relative to the coordinate grid.


In [3]:
# Grid Stuff

# Domain length scale
Lx, Ly = 8.0, 8.0
# Number of cells in each direction
numX, numY = 128, 128
# grid spacing (Δx, Δy not actually dx or dy)
dx = Lx/numX
dy = Ly/numY
X, Y = np.meshgrid(np.linspace(0, Lx, numX+4), np.linspace(0, Ly, numY+4))

In [2]:
# Time Stuff

def lapse_func():
    return

In [3]:
# Number of grid points
Nx = 100
# Domain length
L = 1.0
# Grid spacing
dx = L / Nx
# Time step
dt = 0.0001
# Total time
t_final = 0.1

x = np.linspace(0, L, Nx)
rho = np.ones(Nx)
u = np.zeros(Nx)
p = np.ones(Nx)

rho[x < 0.5] = 1.0
p[x < 0.5] = 1.0
rho[x >= 0.5] = 0.125
p[x >= 0.5] = 0.1

In [4]:
#  adiabatic index: gam = Cp/Cv
gamma = 1

In [5]:
class Tensor:
    def __init__(self, vectors, dual_vectors) -> None:
        self.vectors = vectors
        self.dual_vectors = dual_vectors

    def rank(self):
        return (len(self.dual_vectors), len(self.vectors))
    
    def evaluate(self, vectors, dual_vectors):
        return
    
class Geom_at_cell:
    def __init__(self) -> None:
        self.g = np.eye(4)
        

In [6]:
def basis():
    return

def coordinate_transformation():
    """
    Matrix has 16 degrees of freedom
    Metric has 10 dof
    6 remaining dof can be interpreted as exactly the six parameters of the Lorentz group; we know that these 
    leave the canonical form unchanged
    """
    return

def tensor_product():
    return

def parametric_curve():
    """
    Should return something that when given a parameter t \in [0,1], evaluates to a coordinate x^\mu
    """
    return

# np.linalg.det()

def boyer_lindquist(r, M, J, Q):
    """
    Boyer Lindquist Coordinates

    M: mass of black hole
    Q: Charge of bh
    J: Angular Momentum
    a: Kerr parameter
    """
    a=J/M
    disc = r^2 - 2*M*r + a^2 - Q^2
    return

def adjugate():
    return

def cofactor():
    return

Degrees of freedom refer to the number of independent parameters that can vary without violating any constraints in a system. In the context of tensors and transformations, they represent the number of independent components that can be adjusted or set freely.

In [8]:
"""

"""

def initialize_metric():
    return

def compute_metric():
    """
    if the metric is continuous and nondegenerate, its signature wil be the same at every point.
    """
    return

def compute_inverse_metric():
    return

def raise_index(ginv, tensor):
    return

def lower_index(g, tensor):
    return

def contract_tensor(tensor, axis1, axis2):
    """
    
    """
    if tensor.ndim < 2:
        raise ValueError("Tensor must have at least two dimensions for contraction.")
    if axis1 >= tensor.ndim or axis2 >= tensor.ndim or axis1 == axis2:
        raise ValueError("Invalid axes for contraction.")
    letters = 'abcdefghijklmnopqrstuvwxyz'
    subscript = list(letters[:tensor.ndim])
    subscript[axis2] = subscript[axis1] 
    einsum_str = ''.join(subscript) + '->' + ''.join(subscript[i] for i in range(tensor.ndim) if (i != axis1) and (i != axis2))
    return np.einsum(einsum_str, tensor)

def canonical_form(g):
    """
    In this form, components of g become:
    g_μν = diag(-1,-1,...,-1,+1,+1,...,+1,0,0,...,0)

    At any point p \in M, there exists acoordinate system x^{\hat{\mu}} in which g_{\hat{\mu}\hat{\nu}} 
    takes its canonical form and the first derivatives all vanish

    Such Coordinates are known as locally inertial coordinates, and the associated basis vectors 
    constitute a local Lorentz frame
    """
    return

def compute_connection(g, g_inv):
    """
    This is specifically the Christoffel Symbol:
    Γ^λ_μν = 1/2 g^λσ (d_μ g_νσ + d_ν g_σμ - d_σ g_μν)
    """
    dim = g_inv.shape[0]
    christ = np.zeros((dim, dim, dim))
    pdg = np.zeros((dim, dim, dim))
    for k in range(dim):
        pdg[:, :, k] = np.gradient(g[:, :, k], axis=k)
    for i in range(dim):
        for j in range(dim):
            for k in range(dim):
                for l in range(dim):
                    christ[i, j, k] += 0.5 * g_inv[i, l] * (pdg[l, j, k] + pdg[l, k, j] - pdg[j, k, l])
    return christ


def compute_ricci_tensor(Riemann):
    """
    """
    return np.einsum('ijik->jk', Riemann)

def compute_ricci_scalar():
    return

def create_projection_tensor(g, U):
    """
    To project a vector orthogonal to U^μ

    P^σ_ν = δ^σ_ν + U^σ g_νμ U^μ
    """
    
    return kronecker_delta + U @ lower_index(g, U)

def compute_torsion():
    """
    Torsion tensor T^λ_μν = Γ^λ_μν - Γ^λ_νμ

    n RC geometry, the connection is typically chosen to be metric-compatible, meaning it preserves the metric under parallel transport: ∇λgμν=0
    """

    return


def line_element(g, dx):
    """
    Evaluates metric as a two form:

    ds^2 = g_μν dx^μ dx^ν 
    """
    return g @ dx @ dx.T

def commutator(X, Y):
    """
    [X,Y]^μ = X^λd_λY^μ -  Y^λd_λ^Xμ 
    """
    return


In [9]:
Riemann = np.random.rand(4, 4, 4, 4)
print(compute_ricci_tensor(Riemann))
print(contract_tensor(Riemann, 0, 2))

[[1.98106472 2.04425452 2.24807701 0.85179726]
 [1.79984659 2.05841207 2.15967139 1.812399  ]
 [3.31553349 1.83269204 2.31560046 1.31277916]
 [1.44400269 3.13035196 2.27844985 1.73434679]]
[[1.98106472 2.04425452 2.24807701 0.85179726]
 [1.79984659 2.05841207 2.15967139 1.812399  ]
 [3.31553349 1.83269204 2.31560046 1.31277916]
 [1.44400269 3.13035196 2.27844985 1.73434679]]


In [10]:
def metric_check(g, ginv):
    return g @ ginv

def check_metric_compatible():
    return

##### Mercator Projection Using Coordinate Transforms

In [ ]:
"""

"""

##### Using a Given Geometry and Plotting Partials and Gradients ((Coordinate?) Bases)

In [ ]:
"""

"""

##### Expanding Universe

In [ ]:
"""

"""

##### Creating Mathematical Mapping Figures With Code